version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/build
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/deploy_no_stop.sh
      timeout: 180
      runas: ubuntu
      enviroments:
        WAS_IP: ${{ secrets.WAS_IP }}
        NGINX_IP: ${{ secrets.NGINX_IP }}
