name: checkStyle

on: [ push, pull_request ]

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: setup Gradle permission
        run: chmod +x gradlew
      - name: Run Checkstyle
        run: ./gradlew checkstyleMain
