name: deploy-release

on:
  push:
    branches: [ release ]
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: make secret envfiles for prod
        run: |
          echo "${{secrets.PROD_DB_ENV}}" > ./prod_db_info.env
          echo "${{secrets.SENSITIVE_RELEASE_ENV}}" > ./sensitive_release.env


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: ap-northeast-2

      - name: Upload to AWS S3
        run: |
          aws deploy push \
            --application-name hype-deploy \
            --ignore-hidden-files \
            --s3-location s3://devcourse-pearls-bucket/$GITHUB_SHA.zip \
            --source .

      - name: Code Deploy
        run: aws deploy create-deployment --application-name hype-deploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name hype-prod-group-1
          --s3-location bucket=devcourse-pearls-bucket,bundleType=zip,key=$GITHUB_SHA.zip
